version: '3.8'

services:
  # Workflow Agent
  workflow-agent:
    build:
      context: ./workflow_agent
      dockerfile: Dockerfile
    container_name: risk-workflow-agent
    ports:
      - "8080:8080"
    environment:
      - AGENT_NAME=RiskWorkflowAgent
      - RISK_API_URL=https://risk-api-server-xxx.a.run.app
      - PLAYER_AGENT_URLS=["http://player-agent-1:8080/.well-known/agent.json","http://player-agent-2:8080/.well-known/agent.json","http://player-agent-3:8080/.well-known/agent.json","http://player-agent-4:8080/.well-known/agent.json"]
    restart: unless-stopped

  # Player Agent 1
  player-agent-1:
    build:
      context: ./player_agent
      dockerfile: Dockerfile
    container_name: risk-player-agent-1
    ports:
      - "8081:8080"
    environment:
      - AGENT_NAME=Player1
      - MCP_SERVER_URL=https://risk-mcp-server-xxx.a.run.app/mcp/stream
    restart: unless-stopped

  # Player Agent 2
  player-agent-2:
    build:
      context: ./player_agent
      dockerfile: Dockerfile
    container_name: risk-player-agent-2
    ports:
      - "8082:8080"
    environment:
      - AGENT_NAME=Player2
      - MCP_SERVER_URL=https://risk-mcp-server-xxx.a.run.app/mcp/stream
    restart: unless-stopped

  # Player Agent 3
  player-agent-3:
    build:
      context: ./player_agent
      dockerfile: Dockerfile
    container_name: risk-player-agent-3
    ports:
      - "8085:8080"
    environment:
      - AGENT_NAME=Player3
      - MCP_SERVER_URL=https://risk-mcp-server-xxx.a.run.app/mcp/stream
    restart: unless-stopped

  # Player Agent 4
  player-agent-4:
    build:
      context: ./player_agent
      dockerfile: Dockerfile
    container_name: risk-player-agent-4
    ports:
      - "8086:8080"
    environment:
      - AGENT_NAME=Player4
      - MCP_SERVER_URL=https://risk-mcp-server-xxx.a.run.app/mcp/stream
    restart: unless-stopped 